
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: grievance-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: grievance_portal
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - grievance-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: grievance-backend-prod
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: grievance_portal
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - grievance-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: grievance-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - grievance-network

volumes:
  mysql_data:

networks:
  grievance-network:
    driver: bridge
