
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: grievance-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grievance_portal
      MYSQL_USER: grievance_user
      MYSQL_PASSWORD: grievance_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - grievance-network

  backend:
    build: ./backend
    container_name: grievance-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: grievance_user
      DB_PASSWORD: grievance_password
      DB_NAME: grievance_portal
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - grievance-network

  frontend:
    build: ./frontend
    container_name: grievance-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - grievance-network

volumes:
  mysql_data:

networks:
  grievance-network:
    driver: bridge
