
export interface User {
  id: string; // UUID - auto-generated by Supabase
  userId: string; // Manual numeric ID for internal use
  name: string;
  email: string;
  phone: string;
  employeeId: string;
  city: string;
  cluster: string;
  manager: string;
  role: string; // Changed from "employee" | "admin" to string to accommodate more roles
  password: string;
  dateOfJoining?: string;
  bloodGroup?: string;
  dateOfBirth?: string;
  accountNumber?: string;
  ifscCode?: string;
}

export interface Issue {
  id: string;
  employeeUuid: string; // Changed from userId to employeeUuid
  typeId: string;
  subTypeId: string;
  description: string;
  status: "open" | "in_progress" | "resolved" | "closed";
  priority: "low" | "medium" | "high" | "critical"; // Updated to include "critical"
  createdAt: string;
  updatedAt: string;
  closedAt?: string;
  assignedTo?: string;
  comments: IssueComment[];
  lastStatusChangeAt?: string; // New field to track when status last changed
  reopenableUntil?: string; // New field to track until when ticket can be reopened
  previouslyClosedAt?: string[]; // Track history of closures for reopened tickets
  attachmentUrl?: string | null; // Field to store primary attachment URL
  attachments?: string[] | null; // Array of all attachment URLs
  // Add mapped fields
  mappedTypeId?: string; // Field to store mapped type
  mappedSubTypeId?: string; // Field to store mapped subtype
  mappedAt?: string; // When the issue was mapped
  mappedBy?: string; // Who mapped the issue
  city?: string; // Added city field for analytics
}

export interface IssueComment {
  id: string;
  employeeUuid: string; 
  content: string;
  createdAt: string;
}

export interface AuthState {
  isAuthenticated: boolean;
  user: User | null;
  role: string | null; // Changed from specific type to string
}

// Add IssueAnalytics interface
export interface IssueAnalytics {
  totalIssues: number;
  openIssues: number;
  resolvedIssues: number;
  inProgressIssues: number;
  highPriorityIssues: number;
  issuesByType: { [key: string]: number };
  issuesByCity: { [key: string]: number };
}

// Add a new interface for CSV employee data
export interface CSVEmployeeData {
  id?: string;   // Optional - UUID, auto-generated by Supabase
  userId: string; // Manual numeric ID for internal use
  emp_id: string;
  name: string;
  email: string;
  phone?: string | null;
  city?: string | null;
  cluster?: string | null;
  role: string;
  manager?: string | null;
  date_of_joining?: string | null;
  date_of_birth?: string | null;
  blood_group?: string | null;
  account_number?: string | null;
  ifsc_code?: string | null;
  password?: string;
}

// Row data interface - explicitly defined with all fields as strings
export interface RowData {
  id: string;    // UUID
  userId: string; // Manual numeric ID
  emp_id: string;
  name: string;
  email: string;
  phone: string;
  city: string;
  cluster: string;
  role: string;
  manager: string;
  date_of_joining: string;
  date_of_birth: string;
  blood_group: string;
  account_number: string;
  ifsc_code: string;
  password: string;  // Added password field
}

// Define a string-indexed interface for edited rows
export interface EditedRowsRecord {
  [key: string]: RowData;
}

export interface ValidationError {
  row: CSVEmployeeData;
  errors: string[];
  rowData: RowData;
}

export interface ValidationResult {
  validEmployees: CSVEmployeeData[];
  invalidRows: ValidationError[];
}

export interface DashboardUser {
  id: string;
  name: string;
  email: string;
  employee_id: string | null;
  user_id: string | null;
  phone: string | null;
  city: string | null;
  cluster: string | null;
  manager: string | null;
  role: string;
  created_at: string | null;
  updated_at: string | null;
}
