export interface User {
  id: string; // UUID - auto-generated by Supabase
  userId: string; // Manual numeric ID for internal use
  name: string;
  email: string;
  phone: string;
  employeeId: string;
  city: string;
  cluster: string;
  manager: string;
  role: string; // Changed from "employee" | "admin" to string to accommodate more roles
  password: string;
  dateOfJoining?: string;
  bloodGroup?: string;
  dateOfBirth?: string;
  accountNumber?: string;
  ifscCode?: string;
}

export interface Issue {
  id: string;
  userId: string;
  typeId: string;
  subTypeId: string;
  description: string;
  status: "open" | "in_progress" | "resolved" | "closed";
  priority: "low" | "medium" | "high";
  createdAt: string;
  updatedAt: string;
  closedAt?: string;
  assignedTo?: string;
  comments: IssueComment[];
}

export interface IssueComment {
  id: string;
  userId: string;
  content: string;
  createdAt: string;
}

export interface AuthState {
  isAuthenticated: boolean;
  user: User | null;
  role: string | null; // Changed from specific type to string
}

// Import the DashboardRole from services/dashboardRoleService
import { DashboardRole } from '@/services/dashboardRoleService';

// Update the DashboardUser interface to match our new requirements
export interface DashboardUser {
  id: string;
  name: string;
  email: string;
  emp_id: string;
  role: DashboardRole;
  phone?: string;
  city?: string;
  cluster?: string;
  manager?: string;
}

// Add a new interface for CSV employee data
export interface CSVEmployeeData {
  id?: string;   // Optional - UUID, auto-generated by Supabase
  userId: string; // Manual numeric ID for internal use
  emp_id: string;
  name: string;
  email: string;
  phone?: string | null;
  city?: string | null;
  cluster?: string | null;
  role: string;
  manager?: string | null;
  password?: string;
}

// Row data interface - simplified to match required fields
export interface RowData {
  id: string;    // UUID
  userId: string; // Manual numeric ID
  emp_id: string;
  name: string;
  email: string;
  phone: string;
  city: string;
  cluster: string;
  role: string;
  manager: string;
  password: string;
}

// Define a string-indexed interface for edited rows
export interface EditedRowsRecord {
  [key: string]: RowData;
}

export interface ValidationError {
  row: CSVEmployeeData;
  errors: string[];
  rowData: RowData;
}

export interface ValidationResult {
  validEmployees: CSVEmployeeData[];
  invalidRows: ValidationError[];
}
