
import Papa from 'papaparse';
import { CSVEmployeeData, RowData, ValidationResult } from '@/types';
import { validateEmployeeData } from './validationUtils';

/**
 * Parses and validates a CSV file containing employee data
 */
export const parseEmployeeCSV = (file: File): Promise<ValidationResult> => {
  return new Promise((resolve, reject) => {
    Papa.parse<Record<string, string>>(file, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        const validEmployees: CSVEmployeeData[] = [];
        const invalidRows: {row: CSVEmployeeData, errors: string[], rowData: RowData}[] = [];
        
        // Debug: Log the parse results
        console.log(`CSV parse complete. Found ${results.data.length} rows:`, results);
        
        // Process each row
        results.data.forEach((row, index) => {
          // Skip empty rows
          if (Object.values(row).every(val => val === null || val === '')) {
            return;
          }
          
          // Check multiple possible header names for user_id field with better detection
          // This handles different header variations including "User ID" with space
          const userId = 
            row.userId || 
            row.user_id || 
            row.userid || 
            row['User ID'] || 
            row['user id'] || 
            row['USER ID'] || 
            row['UserId'] || 
            '';

          // Check multiple possible header names for emp_id field with better detection
          const empId = (
            row.emp_id || 
            row.empId || 
            row.employee_id || 
            row.employeeId || 
            row.EmployeeID ||
            row['Employee ID'] ||
            row['emp id'] ||
            row['EMP ID'] ||
            ''
          ).trim();
          
          // Convert CSV data to employee format - exclude id field so Supabase will auto-generate a UUID
          const employeeData: CSVEmployeeData = {
            userId: userId, 
            emp_id: empId,
            name: row.name || '',
            email: row.email || '',
            phone: row.phone || null,
            city: row.city || null,
            cluster: row.cluster || null,
            manager: row.manager || null,
            role: row.role || '',
            password: row.password || 'changeme123',
            dateOfJoining: row.date_of_joining || null,
            dateOfBirth: row.date_of_birth || null,
            bloodGroup: row.blood_group || null,
            accountNumber: row.account_number || null,
            ifscCode: row.ifsc_code || null
          };

          // Generate a structured data object for display
          const rowData: RowData = {
            id: 'Auto-generated', // UUID will be auto-generated by Supabase
            userId: userId, 
            emp_id: empId,
            name: row.name || '',
            email: row.email || '',
            phone: row.phone || '',
            city: row.city || '',
            cluster: row.cluster || '',
            manager: row.manager || '',
            role: row.role || '',
            password: row.password || 'changeme123',
            dateOfJoining: row.date_of_joining || '',
            dateOfBirth: row.date_of_birth || '',
            bloodGroup: row.blood_group || '',
            accountNumber: row.account_number || '',
            ifscCode: row.ifsc_code || ''
          };

          // Validate the data using the common validation function
          const validation = validateEmployeeData({
            ...employeeData,
            user_id: employeeData.userId // Map userId to user_id for validation
          });
          
          if (validation.isValid) {
            validEmployees.push({
              ...employeeData,
              password: employeeData.password || 'changeme123' // Ensure password is set
            });
          } else {
            invalidRows.push({ 
              row: {
                ...employeeData
              }, 
              errors: validation.errors,
              rowData
            });
          }
        });

        console.log('Validation complete:', {
          validEmployees: validEmployees.length,
          invalidRows: invalidRows.length
        });
        
        // Debug: Log the valid employees for troubleshooting
        if (validEmployees.length > 0) {
          console.log('Valid employees ready for upload:', validEmployees);
        }

        resolve({ validEmployees, invalidRows });
      },
      error: (error) => {
        console.error('CSV parsing error:', error);
        reject(error);
      }
    });
  });
};
